@echo off
REM WorkBuddy2API launcher (generated by control_panel.py - ASCII only)
cd /d "%~dp0"
echo Freeing port 8080 if occupied ...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr ":8080" ^| findstr "LISTENING"') do (
    taskkill /f /pid %%a >nul 2>&1
)
timeout /t 1 >nul
echo Starting WorkBuddy2API on :8080 ...
title WorkBuddy2API
wb2api.exe -config config.json
